### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by buruhsd** [DigitalWheat/Multi-Domain-Laravel#3]
hi, im new in laravel. when i try using homestead and using ngrok and open ngrok url it shown 

> Sorry, the page you are looking for could not be found.

and when i try to open app.ngrokapps.ngrok.io it shown 

> Tunnel app.9660c663.ngrok.io not found

am i missing something?
 thank you

**Comment by maxkostinevich** [comment]
The issue is related to your ngrok config and not to the app itself. Custom subdomains e.g. XXXXXX.ngrok.io aren't supported in free ngrok account, you'll need to update to their PRO plan to use this feature. The second thing is that ngrok doesn't support 4th level domains e.g. XXX.yourapp.nbgrok.io, you'll need to use something like app1.ngrok.io/app2.ngrok.io/app3.ngrok.io/etc to test subdomains.

**Comment by buruhsd** [comment]
Okay, thank you

**Comment by marketinghubai** [comment]
HI there!
I have the same issue however, my config looks different:
.env:
APP_NAME=Name
APP_ENV=public

APP_URL=http://app.*******.co
APP_DOMAIN=app.*******.co

SESSION_DOMAIN='.*******.co'

ADMIN_FIRST_NAME=John
ADMIN_LAST_NAME=Doe
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=my_secure_password

The app is hosted on apache webserver with public domain. 
If I visit my app on http://app.*******.co, I see "Sorry, the page you are looking for could not be found."

**Comment by maxkostinevich** [comment]
If your APP_URL is http://app.*****.co then your APP_DOMAIN should be *****.co (without 'app.').
